name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: python -m pip install build

      - name: Setup package
        run: |
          mkdir -p comfyui_embedded_docs/docs/
          cp -r docs/* comfyui_embedded_docs/docs/

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}